platform :ios, '8.0'

def pods
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCPush'
end

target 'examples' do
  pods
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end

